"""init

Revision ID: c8a74304acf8
Revises: 
Create Date: 2024-08-23 23:48:55.190286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a74304acf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('password', sa.String(length=127), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PROFESSOR', 'STUDENT', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('coordinate', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['slug'], ['classes.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'slug', name='constDateClass')
    )
    op.create_table('user_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['register'], ['users.register'], ),
    sa.ForeignKeyConstraint(['slug'], ['classes.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register', sa.Integer(), nullable=False),
    sa.Column('id_call', sa.Integer(), nullable=False),
    sa.Column('coordinate', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_call'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['register'], ['users.register'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('register', 'id_call', name='constUserCall')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencies')
    op.drop_table('user_class')
    op.drop_table('calls')
    op.drop_table('users')
    op.drop_table('classes')
    # ### end Alembic commands ###
